<?php

/* Div PHP Template Engine Dialect - Generated by Div Dialect Creator - Last update 2013-06-08 */ 

/* IMPORTANT!: Include this file before you include div.php */

define('DIV_TAG_REPLACEMENT_PREFIX', '<');                                            define('DIV_TAG_REPLACEMENT_SUFFIX', '/>'); 
define('DIV_TAG_MULTI_MODIFIERS_PREFIX', '<show:');                                   define('DIV_TAG_MULTI_MODIFIERS_SEPARATOR', ':'); 
define('DIV_TAG_MULTI_MODIFIERS_OPERATOR', ':');                                      define('DIV_TAG_MULTI_MODIFIERS_SUFFIX', '/>'); 
define('DIV_TAG_MODIFIER_SIMPLE', 'show:');                                           define('DIV_TAG_MODIFIER_CAPITALIZE_FIRST', 'ucfirst:'); 
define('DIV_TAG_MODIFIER_CAPITALIZE_WORDS', 'ucwords:');                              define('DIV_TAG_MODIFIER_UPPERCASE', 'upper:'); 
define('DIV_TAG_MODIFIER_LOWERCASE', 'lower:');                                       define('DIV_TAG_MODIFIER_LENGTH', 'length:'); 
define('DIV_TAG_MODIFIER_COUNT_WORDS', 'cwords:');                                    define('DIV_TAG_MODIFIER_COUNT_SENTENCES', 'csentences:'); 
define('DIV_TAG_MODIFIER_COUNT_PARAGRAPHS', 'cparagraphs:');                          define('DIV_TAG_MODIFIER_ENCODE_URL', 'urlencode:'); 
define('DIV_TAG_MODIFIER_ENCODE_RAW_URL', 'rawurlencode:');                           define('DIV_TAG_MODIFIER_TRUNCATE', 'truncate:'); 
define('DIV_TAG_MODIFIER_WORDWRAP', 'wrap:');                                         define('DIV_TAG_MODIFIER_SUBSTRING_SEPARATOR', ':'); 
define('DIV_TAG_MODIFIER_SINGLE_QUOTES', 'escape:');                                  define('DIV_TAG_FORMULA_BEGIN', '<formula>'); 
define('DIV_TAG_FORMULA_END', '</formula>');                                          define('DIV_TAG_FORMULA_FORMAT_SEPARATOR', '<format/>'); 
define('DIV_TAG_SUBPARSER_BEGIN_PREFIX', '<sub:');                                    define('DIV_TAG_SUBPARSER_BEGIN_SUFFIX', '>'); 
define('DIV_TAG_SUBPARSER_END_PREFIX', '</sub:');                                     define('DIV_TAG_SUBPARSER_END_SUFFIX', '>'); 
define('DIV_TAG_IGNORE_BEGIN', '<ignore>');                                           define('DIV_TAG_IGNORE_END', '</ignore>'); 
define('DIV_TAG_TXT_BEGIN', '<txt>');                                                 define('DIV_TAG_TXT_END', '</txt>'); 
define('DIV_TAG_TXT_WIDTH_SEPARATOR', '<width/>');                                    define('DIV_TAG_STRIP_BEGIN', '<strip>'); 
define('DIV_TAG_STRIP_END', '</strip>');                                              define('DIV_TAG_LOOP_BEGIN_PREFIX', '<loop:'); 
define('DIV_TAG_LOOP_BEGIN_SUFFIX', '>');                                             define('DIV_TAG_LOOP_END_PREFIX', '</loop:'); 
define('DIV_TAG_LOOP_END_SUFFIX', '>');                                               define('DIV_TAG_EMPTY', '<empty/>'); 
define('DIV_TAG_BREAK', '<break/>');                                                  define('DIV_TAG_LOOP_VAR_SEPARATOR', '<go/>'); 
define('DIV_TAG_ITERATION_BEGIN_PREFIX', '<for>');                                    define('DIV_TAG_ITERATION_BEGIN_SUFFIX', '<go/>'); 
define('DIV_TAG_ITERATION_END', '</for>');                                            define('DIV_TAG_ITERATION_PARAM_SEPARATOR', ':'); 
define('DIV_TAG_CONDITIONAL_TRUE_BEGIN_PREFIX', '<if:');                              define('DIV_TAG_CONDITIONAL_TRUE_BEGIN_SUFFIX', '>'); 
define('DIV_TAG_CONDITIONAL_TRUE_END_PREFIX', '</if:');                               define('DIV_TAG_CONDITIONAL_TRUE_END_SUFFIX', '>'); 
define('DIV_TAG_CONDITIONAL_FALSE_BEGIN_PREFIX', '<ifnot:');                          define('DIV_TAG_CONDITIONAL_FALSE_BEGIN_SUFFIX', '>'); 
define('DIV_TAG_CONDITIONAL_FALSE_END_PREFIX', '</ifnot:');                           define('DIV_TAG_CONDITIONAL_FALSE_END_SUFFIX', '>'); 
define('DIV_TAG_ELSE', '<else/>');                                                    define('DIV_TAG_CONDITIONS_BEGIN_PREFIX', '<if>'); 
define('DIV_TAG_CONDITIONS_BEGIN_SUFFIX', '<then/>');                                 define('DIV_TAG_CONDITIONS_END', '</if>'); 
define('DIV_TAG_TPLVAR_BEGIN', '<var>');                                              define('DIV_TAG_TPLVAR_END', '</var>'); 
define('DIV_TAG_TPLVAR_ASSIGN_OPERATOR', ' =');                                       define('DIV_TAG_DEFAULT_REPLACEMENT_BEGIN', '<default>'); 
define('DIV_TAG_DEFAULT_REPLACEMENT_END', '</default>');                              define('DIV_TAG_INCLUDE_BEGIN', '<include>'); 
define('DIV_TAG_INCLUDE_END', '</include>');                                          define('DIV_TAG_PREPROCESSED_BEGIN', '<preprocess>'); 
define('DIV_TAG_PREPROCESSED_END', '</preprocess>');                                  define('DIV_TAG_CAPSULE_BEGIN_PREFIX', '<capsule:'); 
define('DIV_TAG_CAPSULE_BEGIN_SUFFIX', '>');                                          define('DIV_TAG_CAPSULE_END_PREFIX', '</capsule:'); 
define('DIV_TAG_CAPSULE_END_SUFFIX', '>');                                            define('DIV_TAG_MULTI_REPLACEMENT_BEGIN_PREFIX', '<replace:'); 
define('DIV_TAG_MULTI_REPLACEMENT_BEGIN_SUFFIX', '>');                                define('DIV_TAG_MULTI_REPLACEMENT_END_PREFIX', '</replace'); 
define('DIV_TAG_MULTI_REPLACEMENT_END_SUFFIX', '>');                                  define('DIV_TAG_AGGREGATE_FUNCTION_PROPERTY_SEPARATOR', ':'); 
define('DIV_TAG_LOCATION_BEGIN', '<location> ');                                      define('DIV_TAG_LOCATION_END', '</location>'); 
define('DIV_TAG_LOCATION_CONTENT_BEGIN_PREFIX', '<locate:');                          define('DIV_TAG_LOCATION_CONTENT_BEGIN_SUFFIX', '>'); 
define('DIV_TAG_LOCATION_CONTENT_END_PREFIX', '</locate:');                           define('DIV_TAG_LOCATION_CONTENT_END_SUFFIX', '>'); 
define('DIV_TAG_SPECIAL_REPLACE_NEW_LINE', '&newline;');                              define('DIV_TAG_SPECIAL_REPLACE_CAR_RETURN', '&return;'); 
define('DIV_TAG_SPECIAL_REPLACE_HORIZONTAL_TAB', '&tab;');                            define('DIV_TAG_SPECIAL_REPLACE_VERTICAL_TAB', '&vtab;'); 
define('DIV_TAG_SPECIAL_REPLACE_NEXT_PAGE', '&nextpage;');                            define('DIV_TAG_SPECIAL_REPLACE_DOLLAR_SYMBOL', '&dollar;'); 

// End of file